export const authConstants = {
  LOGIN_REQUEST: 'LOGIN_REQUEST',
  LOGIN_SUCCESS: 'LOGIN_SUCCESS',
  LOGIN_FAILURE: 'LOGIN_FAILURE',
  LOGOUT_REQUEST: 'LOGOUT_REQUEST',
  LOGOUT_SUCCESS: 'LOGOUT_SUCCESS',
  LOGOUT_FAILURE: 'LOGOUT_FAILURE',
}

export const userContants = {
  USER_REGISTER_REQUEST: 'USER_REGISTER_REQUEST',
  USER_REGISTER_SUCCESS: 'USER_REGISTER_SUCCESS',
  USER_REGISTER_FAILURE: 'USER_REGISTER_FAILURE',
}

export const initialDataConstants = {
  GET_ALL_INITIAL_DATA_REQUEST: 'GET_ALL_INITIAL_DATA_REQUEST',
  GET_ALL_INITIAL_DATA_SUCCESS: 'GET_ALL_INITIAL_DATA_SUCCESS',
  GET_ALL_INITIAL_DATA_FAILURE: 'GET_ALL_INITIAL_DATA_FAILURE',
}

export const mainContants = {
  GET_MAIN_PAGE_REQUEST: 'GET_MAIN_PAGE_REQUEST',
  GET_MAIN_PAGE_SUCCESS: 'GET_MAIN_PAGE_SUCCESS',
  GET_MAIN_PAGE_FAILURE: 'GET_MAIN_PAGE_FAILURE',

  ADD_MAIN_PAGE_REQUEST: 'ADD_MAIN_PAGE_REQUEST',
  ADD_MAIN_PAGE_SUCCESS: 'ADD_MAIN_PAGE_SUCCESS',
  ADD_MAIN_PAGE_FAILURE: 'ADD_MAIN_PAGE_FAILURE',

  DELETE_MAIN_PAGE_REQUEST: 'DELETE_MAIN_PAGE_REQUEST',
  DELETE_MAIN_PAGE_SUCCESS: 'DELETE_MAIN_PAGE_SUCCESS',
  DELETE_MAIN_PAGE_FAILURE: 'DELETE_MAIN_PAGE_FAILURE',
}
