export const authConstants = {
  LOGIN_REQUEST: 'LOGIN_REQUEST',
  LOGIN_SUCCESS: 'LOGIN_SUCCESS',
  LOGIN_FAILURE: 'LOGIN_FAILURE',
  LOGOUT_REQUEST: 'LOGOUT_REQUEST',
  LOGOUT_SUCCESS: 'LOGOUT_SUCCESS',
  LOGOUT_FAILURE: 'LOGOUT_FAILURE',
}

export const userContants = {
  USER_REGISTER_REQUEST: 'USER_REGISTER_REQUEST',
  USER_REGISTER_SUCCESS: 'USER_REGISTER_SUCCESS',
  USER_REGISTER_FAILURE: 'USER_REGISTER_FAILURE',
}

export const mainContants = {
  GET_MAIN_PAGE_REQUEST: 'GET_MAIN_PAGE_REQUEST',
  GET_MAIN_PAGE_SUCCESS: 'GET_MAIN_PAGE_SUCCESS',
  GET_MAIN_PAGE_FAILURE: 'GET_MAIN_PAGE_FAILURE',

  VISIT_SPLASH_PAGE_SUCCESS: 'VISIT_SPLASH_SUCCESS',
  VISIT_SPLASH_PAGE_FAILURE: 'VISIT_SPLASH_FAILURE',
}

export const taskContants = {
  ADD_TASK_REQUEST: 'ADD_TASK_REQUEST',
  ADD_TASK_SUCCESS: 'ADD_TASK_SUCCESS',
  ADD_TASK_FAILURE: 'ADD_TASK_FAILURE',

  DELETE_TASK_REQUEST: 'DELETE_TASK_REQUEST',
  DELETE_TASK_SUCCESS: 'DELETE_TASK_SUCCESS',
  DELETE_TASK_FAILURE: 'DELETE_TASK_FAILURE',

  CHANGE_TASK_REQUEST: 'CHANGE_TASK_REQUEST',
  CHANGE_TASK_SUCCESS: 'CHANGE_TASK_SUCCESS',
  CHANGE_TASK_FAILURE: 'CHANGE_TASK_FAILURE',
}
